/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BomradarComponent {
    'disableCopyright': boolean;
    'disableText': boolean;
    'height': number;
    'imagecount': string;
    'play': () => Promise<void>;
    'product': string;
    'setFPS': (fps: number) => void;
    'setOverlays': (ovl: string[]) => void;
    'setPauseTime': (t: number) => void;
    'stop': () => void;
    'width': number;
  }
  interface BomradarComponentAttributes extends StencilHTMLAttributes {
    'disableCopyright'?: boolean;
    'disableText'?: boolean;
    'height'?: number;
    'imagecount'?: string;
    'product'?: string;
    'width'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BomradarComponent': Components.BomradarComponent;
  }

  interface StencilIntrinsicElements {
    'bomradar-component': Components.BomradarComponentAttributes;
  }


  interface HTMLBomradarComponentElement extends Components.BomradarComponent, HTMLStencilElement {}
  var HTMLBomradarComponentElement: {
    prototype: HTMLBomradarComponentElement;
    new (): HTMLBomradarComponentElement;
  };

  interface HTMLElementTagNameMap {
    'bomradar-component': HTMLBomradarComponentElement
  }

  interface ElementTagNameMap {
    'bomradar-component': HTMLBomradarComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
